// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WonderfullOffers.Infraestructure.Entities;

#nullable disable

namespace WonderfullOffers.Infraestructure.Migrations
{
    [DbContext(typeof(CompanyContext))]
    partial class CompanyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WonderfullOffers.Infraestructure.Entities.Models.AmazonOfferEntity", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Coupon")
                        .HasColumnType("int");

                    b.Property<int>("Disccount")
                        .HasColumnType("int");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriceWithinDisccount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PriceWithoutDisccount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TimeSpan")
                        .HasColumnType("datetime2");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Title");

                    b.ToTable("Amazon");
                });

            modelBuilder.Entity("WonderfullOffers.Infraestructure.Entities.Models.DouglasOfferEntity", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Disccount")
                        .HasColumnType("int");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriceWithinDisccount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PriceWithoutDisccount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TimeSpan")
                        .HasColumnType("datetime2");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Title");

                    b.ToTable("Douglas");
                });

            modelBuilder.Entity("WonderfullOffers.Infraestructure.Entities.Models.DruniOfferEntity", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Disccount")
                        .HasColumnType("int");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriceWithinDisccount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PriceWithoutDisccount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TimeSpan")
                        .HasColumnType("datetime2");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Title");

                    b.ToTable("Druni");
                });

            modelBuilder.Entity("WonderfullOffers.Infraestructure.Entities.Models.MaquillaliaOfferEntity", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Disccount")
                        .HasColumnType("int");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriceWithinDisccount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PriceWithoutDisccount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TimeSpan")
                        .HasColumnType("datetime2");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Title");

                    b.ToTable("Maquillalia");
                });

            modelBuilder.Entity("WonderfullOffers.Infraestructure.Entities.Models.PrimorOfferEntity", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Disccount")
                        .HasColumnType("int");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriceWithinDisccount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PriceWithoutDisccount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TimeSpan")
                        .HasColumnType("datetime2");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Title");

                    b.ToTable("Primor");
                });

            modelBuilder.Entity("WonderfullOffers.Infraestructure.Entities.Models.SheinOfferEntity", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Disccount")
                        .HasColumnType("int");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriceWithinDisccount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PriceWithoutDisccount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TimeSpan")
                        .HasColumnType("datetime2");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Title");

                    b.ToTable("Shein");
                });

            modelBuilder.Entity("WonderfullOffers.Infraestructure.Entities.Models.SpringfieldOfferEntity", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Disccount")
                        .HasColumnType("int");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriceWithinDisccount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PriceWithoutDisccount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TimeSpan")
                        .HasColumnType("datetime2");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Title");

                    b.ToTable("Springfield");
                });

            modelBuilder.Entity("WonderfullOffers.Infraestructure.Entities.Models.StradivariusOfferEntity", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Disccount")
                        .HasColumnType("int");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriceWithinDisccount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PriceWithoutDisccount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TimeSpan")
                        .HasColumnType("datetime2");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Title");

                    b.ToTable("Stradivarius");
                });

            modelBuilder.Entity("WonderfullOffers.Infraestructure.Entities.Models.WomensecretOfferEntity", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Disccount")
                        .HasColumnType("int");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriceWithinDisccount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PriceWithoutDisccount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TimeSpan")
                        .HasColumnType("datetime2");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Title");

                    b.ToTable("Womensecret");
                });

            modelBuilder.Entity("WonderfullOffers.Infraestructure.Entities.Models.ZalandoOfferEntity", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Disccount")
                        .HasColumnType("int");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriceWithinDisccount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PriceWithoutDisccount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TimeSpan")
                        .HasColumnType("datetime2");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Title");

                    b.ToTable("Zalando");
                });
#pragma warning restore 612, 618
        }
    }
}
