name: Compilación .Net6, merge with production and upload docker img in docker hub

on:
  push:
    branches: 
      - development

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0

    - name: restore package nuget
      run: dotnet restore

    - name: build project
      run: dotnet build --configuration Release

    - name: Merge to branch 'production'
      run: git merge origin/production

    - name: Push to branch 'production'
      run: git push origin development:production 

    - name: log in in Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build image Docker - production
      run: docker build -t yangolas/wonderfulloffers:1.0 -f Dockerfile.prod .

    - name: Upload image Docker Hub
      run: docker push wonderfulloffersapi
