name: Compilación .Net6, merge with production and upload docker img in docker hub

on:
  push:
    branches: 
      - development

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.302

    - name: restore package nuget
      run: dotnet restore
      working-directory: ./src

    - name: build project
      run: dotnet build --configuration Release
      working-directory: ./src

    - name: log in in Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build image Docker - production
      working-directory: ./src
      run: |
        docker build -t yangolas/wonderfulloffers:1.0 -f Dockerfile.prod .
        docker tag yangolas/wonderfulloffers:1.0 yangolas/wonderfulloffersapi:1.0


    - name: Upload image Docker Hub
      run: docker push yangolas/wonderfulloffersapi:1.0
